version: '3.5'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: LOGIN
      POSTGRES_PASSWORD: PASSWORD
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    ports:
      - 5432:5432
    networks:
      - database
    restart: unless-stopped

networks:
  database:
    driver: bridge

volumes:
  database: